### Contour can be helpful for object detection or object recongintion or shape analysis. So, for finding contours we use binary images.

### Before finding the contour we are going to apply threshold and apply canny edge detection to find the contour on the image

In [1]:
import cv2
import numpy as np


In [8]:
img = cv2.imread("C:\\Users\\KARNDEEP SINGH\\Desktop\\opencv-master\\opencv-master\\samples\\data\\opencv-logo.png")
imggray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, thresh = cv2.threshold(imggray, 127,255, 0)
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
print("Number of contours:" + str(len(contours)))
print(contours[0])

cv2.drawContours(img, contours, -1, (0,255,0), 3) #if we give -1 we can get contours over the whole images and for specific contours we need to pass index i.e for 0th index we pass 0  
cv2.imshow("opencv", img)
cv2.imshow("imageGray", imggray)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of contours:9
[[[158 637]]

 [[157 638]]

 [[156 638]]

 [[155 638]]

 [[154 638]]

 [[153 638]]

 [[152 638]]

 [[151 639]]

 [[150 639]]

 [[149 640]]

 [[148 640]]

 [[147 641]]

 [[147 642]]

 [[146 643]]

 [[146 644]]

 [[145 645]]

 [[145 646]]

 [[145 647]]

 [[145 648]]

 [[144 649]]

 [[144 650]]

 [[144 651]]

 [[144 652]]

 [[144 653]]

 [[144 654]]

 [[144 655]]

 [[144 656]]

 [[144 657]]

 [[143 658]]

 [[143 659]]

 [[143 660]]

 [[143 661]]

 [[143 662]]

 [[143 663]]

 [[143 664]]

 [[143 665]]

 [[143 666]]

 [[143 667]]

 [[143 668]]

 [[144 669]]

 [[144 670]]

 [[144 671]]

 [[144 672]]

 [[144 673]]

 [[144 674]]

 [[144 675]]

 [[144 676]]

 [[144 677]]

 [[145 678]]

 [[145 679]]

 [[145 680]]

 [[145 681]]

 [[146 682]]

 [[146 683]]

 [[147 684]]

 [[148 685]]

 [[149 686]]

 [[150 687]]

 [[151 687]]

 [[152 687]]

 [[153 688]]

 [[154 688]]

 [[155 688]]

 [[156 688]]

 [[157 688]]

 [[158 689]]

 [[159 689]]

 [[160 689]]

 [[161 689]]

 [[162 689]]
